### ISSUE TITLE
how interact with the bot

### ISSUE THREAD

**Issue by grunch** [slaninas/nostr-bot#1]
I'm testing the bot, I run it with a new private key, run ok and I can see in astral.ninja this message

https://astral.ninja/event/7f0cd0cf39436747d6551ed4da608cc72b5f5f83676a80b4e0e73e53f595e259

How can I vote? I need a new client?

**Comment by slaninas** [comment]
Use the astral to reply to the bot's message with !no, !yes or !results.

The poll bot is just a simple example, the number of votes per pubkey is not limited in any way so it doesn't matter what private key you use for the reply.

I tried to respond to the message you linked and it works for me. Let me know if it works for you.

![nostr-bot](https://user-images.githubusercontent.com/2387084/200123126-239aa7fb-d643-4cb8-a691-8b7cde0df654.png)

**Comment by slaninas** [comment]
Ah, I see you just closed it. I hope you made it work :)

**Comment by grunch** [comment]
Yes I tried with that before and it worked, thanks great job, I am trying to make a bot that works like on telegram, when users send messages to the bot the bot respond according to the command the users sent
