### ISSUE TITLE
How to use keypair_from_secret from nsec

### ISSUE THREAD

**Issue by ademar111190** [slaninas/nostr-bot#2]
Could you give an example of how to use the bot library using a "nsec1" key?

**Comment by slaninas** [comment]
See https://github.com/slaninas/nostr-bot/releases/tag/v0.3.0 I just released. It adds support for this. You can now use the "nsec1" instead of the hex format.

**Comment by ademar111190** [comment]
Thank you very much 🙏

**Comment by ademar111190** [comment]
I just wanted to share that I created this little bot https://github.com/ademar111190/Bitac-Nostr-Bot
thank you again for adding the nsec and the whole lib as well 🚀
